### ISSUE TITLE
Fixed Building

### ISSUE THREAD

**Issue by RamboRogers** [raspicamplayer/camplayer#108]
I forked this and updated the readme so you can build and it works for anyone looking here.

https://github.com/RamboRogers/camplayer

**Comment by jesjhoward** [comment]
Can't seem to get your version working. I'm not 100% sure, but it seems to be a problem with piping? --demo never displays to the screen and ends with:
Traceback (most recent call last):
  File "./camplayer.py", line 313, in <module>
    main()
  File "./camplayer.py", line 232, in main
    screenmanager.do_work()
  File "/usr/local/share/camplayer/camplayer/screenmanager.py", line 1183, in do_work
    self._screen_rotate_next_active(display_idx=display_idx)
  File "/usr/local/share/camplayer/camplayer/screenmanager.py", line 992, in _screen_rotate_next_active
    self._screens[display_idx][self._active_screen_idx[display_idx]].layout), display_idx=display_idx)
  File "/usr/local/share/camplayer/camplayer/backgroundgen.py", line 286, in show_background
    cls._proc_background[display_idx].stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe

Any help?

**Comment by RamboRogers** [comment]
did you follow the instructions and run that old buster release?

**Comment by 2wenty2wo** [comment]
Worked perfectly, thank you.

**Comment by Shane8johnson** [comment]
> I forked this and updated the readme so you can build and it works for anyone looking here.
> 
> https://github.com/RamboRogers/camplayer

Thank you for forking this so that it will still work. Could you please update your install instructions to include changing the APT-GET repositories?
I had to do the following before I was able to install git.

`sudo nano /etc/apt/sources.list`
Comment out any existing lines and or replace it with:
```
deb http://legacy.raspbian.org/raspbian/ buster main contrib non-free rpi
deb http://archive.raspberrypi.org/debian/ buster main
```
And then run:
```
sudo apt-get clean
sudo rm -rf /var/lib/apt/lists/*
sudo apt-get update --allow-releaseinfo-change
sudo apt-get install -y git
```

After that, I was able to follow the rest of the install.
Thanks!

**Comment by RamboRogers** [comment]
I guess they took down the old repos, good update
